# Configura qu\u00c3\u00a9 estilo visual usa el juego.
# Este es el UNICO archivo que debe cambiar para alternar entre estilos
# visuales existentes, o para habilitar uno nuevo (una vez creados sus
# productos concretos y su f\u00c3\u00a1brica concreta).
#
# Valores disponibles de f\u00c3\u00a1brica:
#   com.balitechy.spacewar.visual.sprite.SpriteStyleFactory
#   com.balitechy.spacewar.visual.vectorial.VectorialStyleFactory
#   com.balitechy.spacewar.visual.colorfulvectorial.ColorfulVectorialStyleFactory
visual.style.factory=com.balitechy.spacewar.visual.colorfulvectorial.ColorfulVectorialStyleFactory